class BaseGeometry:
    def intersection(self, other: "BaseGeometry") -> "BaseGeometry": ...
    def union(self, other: "BaseGeometry") -> "BaseGeometry": ...
    @property
    def area(self) -> float: ...
