# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/SimonBiggs/nbstripout
    rev: 0a4fa37151ce3c2fb522bf64469224c831a41773
    hooks:
      - id: nbstripout
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb", "500"]
        exclude: ^.*innolitics.*attributes.json$
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
        types: [python]
      - id: isort
        additional_dependencies: ["toml"]
        types: [pyi]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.7
    hooks:
      - id: blackdoc
