[tool.poetry]
name = "rtai-regulatory"
version = "0.1.16"
description = "Radiotherapy AI's Quality Management System"
authors = ["Simon Biggs <simon.biggs@radiotherapy.ai>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
jupyter-book = "^0.12.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
