[tool.poetry]
name = "radiotherapyai"
version = "0.1.0"
description = "AI assisted treatments accessible to all"
authors = ["Simon Biggs <simon.biggs@radiotherapy.ai>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
shapely = "*"
numpy = "*"

[tool.poetry.dev-dependencies]
jupyter-book = "*"
black = "*"
pytest = "*"
pyright = "*"
pylint = "*"
pytest-pylint = "*"
pre-commit = "*"

[tool.poetry.scripts]
radiotherapyai = "radiotherapyai.__main__:app"
rtai = "radiotherapyai.__main__:app"

[tool.pyright]
include = ["radiotherapyai"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
]
typeCheckingMode = "strict"

[tool.isort]
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
