[tool.poetry]
name = "radiotherapyai"
version = "0.1.0"
description = "AI assisted treatments accessible to all"
authors = ["Simon Biggs <simon.biggs@radiotherapy.ai>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
jupyter-book = "*"
black = "*"

[tool.poetry.scripts]
radiotherapyai = "radiotherapyai.__main__:app"
rtai = "radiotherapyai.__main__:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
