# Copyright 2022 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Copied from https://github.com/pantsbuild/pants/blob/bca1b5a4ae311511fe87ff0dd3ccecc32955d024/src/python/pants/_version/BUILD#L1-L6

python_sources()

resources(name="resources", sources=["VERSION"])
