class BaseGeometry:
    def intersection(self, other: "BaseGeometry") -> "BaseGeometry": ...
    @property
    def area(self) -> float: ...

class Polygon(BaseGeometry):
    def __init__(self, shell: list[tuple[float, float]]) -> None: ...
