# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Radiotherapy AI
author: Radiotherapy AI Pty Ltd
copyright: "2021 – 2022"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/RadiotherapyAI/regulatory
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <p>
      <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
        <img
          alt="Creative Commons Licence" style="border-width:0"
          src="https://i.creativecommons.org/l/by/4.0/80x15.png" />
      </a><br />

      This work is licensed under the <a
        rel="license"
        href="http://creativecommons.org/licenses/by/4.0/">Creative Commons
      Attribution 4.0 International License
      </a>
      <br />
      Templates copyright OpenRegulatory (<a rel="license" href="https://openregulatory.com/templates/">originals</a>).
      General content copyright Radiotherapy AI.
    </p>

# sphinx:
#   extra_extensions:
#     - sphinxcontrib.excel


parse:
  myst_substitutions:
    device_name: "Radiotherapy AI Contour Recommendations"
    device_version: "`v0.1.17`"
    device_manufacturer: "Radiotherapy AI"
