name: Main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Perform CI Checks

    runs-on: ubuntu-20.04
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3

      - uses: pantsbuild/actions/init-pants@v2
        with:
          pants-python-version: ${{ matrix.python-version }}
          gha-cache-key: cache0-py${{ matrix.python-version }}
          named-caches-hash: ${{ hashFiles('3rdparty/python/default.lock') }}
          cache-lmdb-store: "false"

      - name: Check BUILD files
        run: ./pants tailor --check update-build-files --check ::

      - name: Lint and typecheck
        run: |
          ./pants lint check ::

      - name: Test
        run: |
          ./pants test ::

      - name: Package
        run: |
          ./pants package ::

      # TODO: Add docs building back in

      # - name: Build docs
      #   if: matrix.task == 'docs'
      #   run: |
      #     [[ ! -d docs/_build/html ]]
      #     poetry run rai docs
      #     [[ -d docs/_build/html ]]

      # - name: Add GitHub Pages config files
      #   if: github.event_name == 'push' && matrix.task == 'docs'
      #   run: |
      #     echo docs.radiotherapy.ai > docs/_build/html/CNAME
      #     touch docs/_build/html/.nojekyll

      # - name: Deploy to gh-pages branch
      #   if: github.event_name == 'push' && matrix.task == 'docs'
      #   uses: JamesIves/github-pages-deploy-action@4.1.3
      #   with:
      #     branch: gh-pages
      #     folder: docs/_build/html
